services:
  - type: web
    name: flask-sqli-scanner
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api:app
    envVars:
      - key: FLASK_ENV
        value: production
